/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ManuelJeitinhoRouteImport } from './routes/manuel-jeitinho'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AuteursIndexRouteImport } from './routes/auteurs.index'
import { Route as BlogRechercheRouteImport } from './routes/blog.recherche'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuteursSlugRouteImport } from './routes/auteurs.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as BlogCategorieSlugRouteImport } from './routes/blog.categorie.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ManuelJeitinhoRoute = ManuelJeitinhoRouteImport.update({
  id: '/manuel-jeitinho',
  path: '/manuel-jeitinho',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuteursIndexRoute = AuteursIndexRouteImport.update({
  id: '/auteurs/',
  path: '/auteurs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRechercheRoute = BlogRechercheRouteImport.update({
  id: '/blog/recherche',
  path: '/blog/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuteursSlugRoute = AuteursSlugRouteImport.update({
  id: '/auteurs/$slug',
  path: '/auteurs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCategorieSlugRoute = BlogCategorieSlugRouteImport.update({
  id: '/blog/categorie/$slug',
  path: '/blog/categorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/manuel-jeitinho': typeof ManuelJeitinhoRoute
  '/mcp': typeof McpRoute
  '/partenaires': typeof PartenairesRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auteurs/$slug': typeof AuteursSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/recherche': typeof BlogRechercheRoute
  '/auteurs/': typeof AuteursIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/blog/categorie/$slug': typeof BlogCategorieSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/manuel-jeitinho': typeof ManuelJeitinhoRoute
  '/mcp': typeof McpRoute
  '/partenaires': typeof PartenairesRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auteurs/$slug': typeof AuteursSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/recherche': typeof BlogRechercheRoute
  '/auteurs': typeof AuteursIndexRoute
  '/blog': typeof BlogIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/blog/categorie/$slug': typeof BlogCategorieSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/manuel-jeitinho': typeof ManuelJeitinhoRoute
  '/mcp': typeof McpRoute
  '/partenaires': typeof PartenairesRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auteurs/$slug': typeof AuteursSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/recherche': typeof BlogRechercheRoute
  '/auteurs/': typeof AuteursIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/blog/categorie/$slug': typeof BlogCategorieSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/manuel-jeitinho'
    | '/mcp'
    | '/partenaires'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auteurs/$slug'
    | '/blog/$slug'
    | '/blog/recherche'
    | '/auteurs/'
    | '/blog/'
    | '/.mcp/invoke-tool/$tool'
    | '/blog/categorie/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/manuel-jeitinho'
    | '/mcp'
    | '/partenaires'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auteurs/$slug'
    | '/blog/$slug'
    | '/blog/recherche'
    | '/auteurs'
    | '/blog'
    | '/.mcp/invoke-tool/$tool'
    | '/blog/categorie/$slug'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/manuel-jeitinho'
    | '/mcp'
    | '/partenaires'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auteurs/$slug'
    | '/blog/$slug'
    | '/blog/recherche'
    | '/auteurs/'
    | '/blog/'
    | '/.mcp/invoke-tool/$tool'
    | '/blog/categorie/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  ManuelJeitinhoRoute: typeof ManuelJeitinhoRoute
  McpRoute: typeof McpRoute
  PartenairesRoute: typeof PartenairesRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AuteursSlugRoute: typeof AuteursSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogRechercheRoute: typeof BlogRechercheRoute
  AuteursIndexRoute: typeof AuteursIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  BlogCategorieSlugRoute: typeof BlogCategorieSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manuel-jeitinho': {
      id: '/manuel-jeitinho'
      path: '/manuel-jeitinho'
      fullPath: '/manuel-jeitinho'
      preLoaderRoute: typeof ManuelJeitinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auteurs/': {
      id: '/auteurs/'
      path: '/auteurs'
      fullPath: '/auteurs/'
      preLoaderRoute: typeof AuteursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/recherche': {
      id: '/blog/recherche'
      path: '/blog/recherche'
      fullPath: '/blog/recherche'
      preLoaderRoute: typeof BlogRechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auteurs/$slug': {
      id: '/auteurs/$slug'
      path: '/auteurs/$slug'
      fullPath: '/auteurs/$slug'
      preLoaderRoute: typeof AuteursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/categorie/$slug': {
      id: '/blog/categorie/$slug'
      path: '/blog/categorie/$slug'
      fullPath: '/blog/categorie/$slug'
      preLoaderRoute: typeof BlogCategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  ManuelJeitinhoRoute: ManuelJeitinhoRoute,
  McpRoute: McpRoute,
  PartenairesRoute: PartenairesRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AuteursSlugRoute: AuteursSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogRechercheRoute: BlogRechercheRoute,
  AuteursIndexRoute: AuteursIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  BlogCategorieSlugRoute: BlogCategorieSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
