/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as ManuelJeitinhoRouteImport } from './routes/manuel-jeitinho'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AuteursIndexRouteImport } from './routes/auteurs.index'
import { Route as BlogRechercheRouteImport } from './routes/blog.recherche'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuteursSlugRouteImport } from './routes/auteurs.$slug'
import { Route as BlogCategorieSlugRouteImport } from './routes/blog.categorie.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ManuelJeitinhoRoute = ManuelJeitinhoRouteImport.update({
  id: '/manuel-jeitinho',
  path: '/manuel-jeitinho',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuteursIndexRoute = AuteursIndexRouteImport.update({
  id: '/auteurs/',
  path: '/auteurs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRechercheRoute = BlogRechercheRouteImport.update({
  id: '/blog/recherche',
  path: '/blog/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuteursSlugRoute = AuteursSlugRouteImport.update({
  id: '/auteurs/$slug',
  path: '/auteurs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorieSlugRoute = BlogCategorieSlugRouteImport.update({
  id: '/blog/categorie/$slug',
  path: '/blog/categorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/manuel-jeitinho': typeof ManuelJeitinhoRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auteurs/$slug': typeof AuteursSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/recherche': typeof BlogRechercheRoute
  '/auteurs/': typeof AuteursIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/categorie/$slug': typeof BlogCategorieSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/manuel-jeitinho': typeof ManuelJeitinhoRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auteurs/$slug': typeof AuteursSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/recherche': typeof BlogRechercheRoute
  '/auteurs': typeof AuteursIndexRoute
  '/blog': typeof BlogIndexRoute
  '/blog/categorie/$slug': typeof BlogCategorieSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/manuel-jeitinho': typeof ManuelJeitinhoRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auteurs/$slug': typeof AuteursSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/recherche': typeof BlogRechercheRoute
  '/auteurs/': typeof AuteursIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/categorie/$slug': typeof BlogCategorieSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/manuel-jeitinho'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/auteurs/$slug'
    | '/blog/$slug'
    | '/blog/recherche'
    | '/auteurs/'
    | '/blog/'
    | '/blog/categorie/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/manuel-jeitinho'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/auteurs/$slug'
    | '/blog/$slug'
    | '/blog/recherche'
    | '/auteurs'
    | '/blog'
    | '/blog/categorie/$slug'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/manuel-jeitinho'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/auteurs/$slug'
    | '/blog/$slug'
    | '/blog/recherche'
    | '/auteurs/'
    | '/blog/'
    | '/blog/categorie/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  ManuelJeitinhoRoute: typeof ManuelJeitinhoRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuteursSlugRoute: typeof AuteursSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogRechercheRoute: typeof BlogRechercheRoute
  AuteursIndexRoute: typeof AuteursIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogCategorieSlugRoute: typeof BlogCategorieSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manuel-jeitinho': {
      id: '/manuel-jeitinho'
      path: '/manuel-jeitinho'
      fullPath: '/manuel-jeitinho'
      preLoaderRoute: typeof ManuelJeitinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auteurs/': {
      id: '/auteurs/'
      path: '/auteurs'
      fullPath: '/auteurs/'
      preLoaderRoute: typeof AuteursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/recherche': {
      id: '/blog/recherche'
      path: '/blog/recherche'
      fullPath: '/blog/recherche'
      preLoaderRoute: typeof BlogRechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auteurs/$slug': {
      id: '/auteurs/$slug'
      path: '/auteurs/$slug'
      fullPath: '/auteurs/$slug'
      preLoaderRoute: typeof AuteursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/categorie/$slug': {
      id: '/blog/categorie/$slug'
      path: '/blog/categorie/$slug'
      fullPath: '/blog/categorie/$slug'
      preLoaderRoute: typeof BlogCategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  ManuelJeitinhoRoute: ManuelJeitinhoRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuteursSlugRoute: AuteursSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogRechercheRoute: BlogRechercheRoute,
  AuteursIndexRoute: AuteursIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogCategorieSlugRoute: BlogCategorieSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
